site_name: MD2K Software Documentation
site_description: mCerbrum and Cerebral Cortex software and API documentation
site_author: Timothy Hnat
copyright: MD2K 2016
google_analytics: ['UA-77812263-1', 'auto']

remote_branch: master

theme: spacelab

site_url: http://md2korg.github.io/


markdown_extensions:
  - smarty

pages:
  - Home:
    - Introduction: index.md
    - Contributing: contributing.md
  - Overview:
    - Data Protection: data_protection.md
    - Contributors: contributors.md
    - References: references.md
    - License: license.md
  - mCerebrum:
    - Overview: mCerebrum/index.md
    - Configurations: mCerebrum/configurations.md
    - Configuration-DataKit: mCerebrum/configuration-datakit.md
    - Configuration-Sensors: mCerebrum/configuration-sensors.md
    - Configuration-Plotter: mCerebrum/configuration-plotter.md
    - Configuration-EMA: mCerebrum/configuration-ema.md
    - Configuration-EMA Scheduler: mCerebrum/configuration-emascheduler.md
    - Troubleshooting: mCerebrum/troubleshooting.md
  - Cerebral Cortex:
    - Overview: cerebralcortex/index.md
    - API: cerebralcortex/api.md
  - Feedback: feedback.md
