site_name: MD2K Software Documentation
site_description: mCerbrum and Cerebral Cortex software and API documentation
site_author: Timothy Hnat
copyright: BSD 2-Clause
google_analytics: ['', 'md2korg.github.io']

theme: readthedocs

site_url: http://md2korg.github.io/

pages:
  - Home: index.md
  - mCerebrum: mCerebrum/index.md
  - Cerebral Cortex:
    - Overview: cerebralcortex/index.md
    - API: cerebralcortex/api.md
  - Data Protection: data_protection.md
  - Contributors: contributors.md
  - License: license.md
  - References: references.md
