site_name: MD2K Software Documentation
site_description: mCerbrum and Cerebral Cortex software and API documentation
site_author: Timothy Hnat
copyright: BSD 2-Clause
google_analytics: ['', 'md2korg.github.io']

remote_branch: master

theme: readthedocs
# theme: bootstrap

site_url: http://md2korg.github.io/


markdown_extensions:
  - smarty

pages:
  - Home: index.md
  - Overview:
    - Data Protection: data_protection.md
    - Contributors: contributors.md
    - References: references.md
    - License: license.md
  - mCerebrum:
    - Overview: mCerebrum/index.md
  - Cerebral Cortex:
    - Overview: cerebralcortex/index.md
    - API: cerebralcortex/api.md
  - Feedback: feedback.md
